# -*- coding: utf-8 -*-
"""*RETRIEVE _SECRETS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16ldkQQDEFV-EeCqv9x99FkTxf9r_pJTA
"""

!pip install cryptography
from google.colab import drive
drive.mount('/content/drive')

!pip install cryptography
from google.colab import drive
drive.mount('/content/drive')

!pip install cryptography
import os
import base64
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.fernet import Fernet, InvalidToken
from cryptography.hazmat.backends import default_backend

def derive_key(password: str, salt: bytes) -> bytes:
    """Derive a key from the password and salt using PBKDF2 HMAC SHA256."""
    kdf = PBKDF2HMAC(
        algorithm=hashes.SHA256(),
        length=32,
        salt=salt,
        iterations=100_000,
        backend=default_backend()
    )
    return base64.urlsafe_b64encode(kdf.derive(password.encode()))

def retrieve_secret(secret_name: str, password: str) -> str:
    """Retrieve and decrypt the secret from Google Drive."""
    filepath = f'/content/drive/MyDrive/secrets/{secret_name}.secret'
    if not os.path.exists(filepath):
        raise FileNotFoundError(f"Secret '{secret_name}' not found.")

    with open(filepath, 'rb') as file:
        data = file.read()
    salt = data[:16]
    encrypted_secret = data[16:]
    key = derive_key(password, salt)
    fernet = Fernet(key)

    try:
        decrypted_secret = fernet.decrypt(encrypted_secret)
        return decrypted_secret.decode()
    except InvalidToken:
        raise ValueError('Invalid password or corrupted secret.')

password = input('Enter the password to decrypt the secret: ')
secret_name = input('Enter the name of the secret: ')

# Retrieve and display the secret
try:
    secret_value = retrieve_secret(secret_name, password)
    #print(f"The secret value is: {secret_value}")
except (FileNotFoundError, ValueError) as e:
    print(e)

